/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ReadDocument;
import controller.util;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
import javax.swing.text.Highlighter.HighlightPainter;
import model.Document;

/**
 *
 * @author Manuel Goncalves Lopez
 */
public class Test extends javax.swing.JFrame {

    
    
      Highlighter highlighter;
      HighlightPainter painter = 
             new DefaultHighlighter.DefaultHighlightPainter(Color.yellow);
      Document document;
    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
        try{
          highlighter=  TA_Text.getHighlighter();
       String path="C:\\Users\\manue\\Desktop\\test.txt";
       ReadDocument read=new ReadDocument(path);
       document=read.getDocument();
       CK_Cargado.setSelected(true);
       TA_Text.setText(document.getText());
       
      highlighter.addHighlight(0, 1, painter );
        }
        catch(Exception ex){
                Logger.getLogger(Test.class.getName()).log(Level.SEVERE, null, ex);
                TA_Text.setText("Archivo Cargado");
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BT_Previous = new javax.swing.JButton();
        BT_Next = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_Text = new javax.swing.JTextArea();
        CK_Cargado = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        BT_Previous.setText("Previous");
        BT_Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_PreviousActionPerformed(evt);
            }
        });

        BT_Next.setText("Next");
        BT_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_NextActionPerformed(evt);
            }
        });

        TA_Text.setColumns(20);
        TA_Text.setRows(5);
        jScrollPane1.setViewportView(TA_Text);

        CK_Cargado.setText("Archivo Cargado");
        CK_Cargado.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BT_Previous)
                        .addGap(18, 18, 18)
                        .addComponent(BT_Next)
                        .addGap(18, 18, 18)
                        .addComponent(CK_Cargado)
                        .addGap(0, 111, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_Next)
                    .addComponent(BT_Previous)
                    .addComponent(CK_Cargado))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_NextActionPerformed
        
          try {
              highlighter.removeAllHighlights();
              int min=document.getNext(util.Layer.LETTER).getId();
              highlighter.addHighlight(min,min+1, painter );
          } catch (BadLocationException ex) {
              Logger.getLogger(Test.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_BT_NextActionPerformed

    private void BT_PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_PreviousActionPerformed
          try {
              highlighter.removeAllHighlights();
              System.out.println("Previous - "+document.getFocusIdChild().getId());
              int min=document.getPrevious(util.Layer.LETTER).getId();
              highlighter.addHighlight(min,min+1, painter );
          } catch (BadLocationException ex) {
              Logger.getLogger(Test.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_BT_PreviousActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
 
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new Test().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Next;
    private javax.swing.JButton BT_Previous;
    private javax.swing.JCheckBox CK_Cargado;
    private javax.swing.JTextArea TA_Text;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
